{
	"version": 1633103491,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bgu-sheet0.png",
		"images/judul-sheet0.png",
		"images/mulai-sheet0.png",
		"images/about-sheet0.png",
		"images/close-sheet0.png",
		"images/musik-sheet0.png",
		"images/musik-sheet1.png",
		"images/bg-sheet0.png",
		"images/belajaraksara-sheet0.png",
		"images/pilihmenu-sheet0.png",
		"images/back-sheet0.png",
		"images/next-sheet0.png",
		"images/prew-sheet0.png",
		"images/ha-sheet0.png",
		"images/na-sheet0.png",
		"images/ca-sheet0.png",
		"images/ra-sheet0.png",
		"images/ka-sheet0.png",
		"images/da-sheet0.png",
		"images/ta-sheet0.png",
		"images/sa-sheet0.png",
		"images/wa-sheet0.png",
		"images/la-sheet0.png",
		"images/ma-sheet0.png",
		"images/ga-sheet0.png",
		"images/ba-sheet0.png",
		"images/nga-sheet0.png",
		"images/pa-sheet0.png",
		"images/ja-sheet0.png",
		"images/ya-sheet0.png",
		"images/nya-sheet0.png",
		"images/ulu-sheet0.png",
		"images/suku-sheet0.png",
		"images/taleng-sheet0.png",
		"images/talengtedong-sheet0.png",
		"images/pepet-sheet0.png",
		"images/cecek-sheet0.png",
		"images/surang-sheet0.png",
		"images/bisah-sheet0.png",
		"images/adegadeg-sheet0.png",
		"images/nania-sheet0.png",
		"images/guwung-sheet0.png",
		"images/sukukembung-sheet0.png",
		"images/unud-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/mame-sheet0.png",
		"images/logomedukasi-sheet0.png",
		"images/logo_rumah_belajar_gab-sheet0.png",
		"images/bawah-sheet0.png",
		"images/nania2-sheet0.png",
		"images/close_-sheet0.png",
		"images/guwung2-sheet0.png",
		"images/sukukembung2-sheet0.png",
		"images/ulu2-sheet0.png",
		"images/suku2-sheet0.png",
		"images/taleng2-sheet0.png",
		"images/talengtedong2-sheet0.png",
		"images/pepet2-sheet0.png",
		"images/cecek2-sheet0.png",
		"images/cecek3-sheet0.png",
		"images/cecek3-sheet1.png",
		"images/surang2-sheet0.png",
		"images/bisah2-sheet0.png",
		"images/bisah3-sheet0.png",
		"images/bisah3-sheet1.png",
		"images/adegadeg2-sheet0.png",
		"images/swipe-sheet0.png",
		"images/m1-sheet0.png",
		"images/bgswipe-sheet0.png",
		"images/ha2-sheet0.png",
		"images/na2-sheet0.png",
		"images/ca2-sheet0.png",
		"images/ra2-sheet0.png",
		"images/ka2-sheet0.png",
		"images/da2-sheet0.png",
		"images/ta2-sheet0.png",
		"images/sa2-sheet0.png",
		"images/wa2-sheet0.png",
		"images/la2-sheet0.png",
		"images/ma2-sheet0.png",
		"images/ga2-sheet0.png",
		"images/ba2-sheet0.png",
		"images/nga2-sheet0.png",
		"images/pa2-sheet0.png",
		"images/ja2-sheet0.png",
		"images/ya2-sheet0.png",
		"images/nya2-sheet0.png",
		"images/pilihbelajar-sheet0.png",
		"images/menuwianjana-sheet0.png",
		"images/menusuara-sheet0.png",
		"images/menutengenan-sheet0.png",
		"images/menuardasuara-sheet0.png",
		"images/aksarawianjana-sheet0.png",
		"images/penganggeardasuara-sheet0.png",
		"images/penganggesuara-sheet0.png",
		"images/penganggetengenan-sheet0.png",
		"images/nulis-sheet0.png",
		"images/permainan-sheet0.png",
		"images/p1-sheet0.png",
		"images/c-sheet0.png",
		"images/a-sheet0.png",
		"images/jam-sheet0.png",
		"images/d-sheet0.png",
		"images/score-sheet0.png",
		"images/b-sheet0.png",
		"images/bgsoal-sheet0.png",
		"images/spritefont.png",
		"images/bgjawaban-sheet0.png",
		"images/gambar_soal-sheet0.png",
		"images/gambar_soal-sheet1.png",
		"images/gambar_soal-sheet2.png",
		"images/btn_benar-sheet0.png",
		"images/btn_benar-sheet1.png",
		"images/bgkalah-sheet0.png",
		"images/trophy-sheet0.png",
		"images/bawah2-sheet0.png",
		"images/medal-sheet0.png",
		"images/kertas-sheet0.png",
		"images/btn_belajarlagi-sheet0.png",
		"images/btn_belajarlagi-sheet1.png",
		"images/btn_belajarlagi-sheet2.png",
		"images/g-sheet0.png",
		"images/bawah4-sheet0.png",
		"images/bgjawaban2-sheet0.png",
		"images/aksaraapakahini_-sheet0.png",
		"images/startengah-sheet0.png",
		"images/starkanan-sheet0.png",
		"images/starkiri-sheet0.png",
		"images/starmenang-sheet0.png",
		"images/logo-sheet0.png",
		"images/loading-sheet0.png",
		"images/load_bg-sheet0.png",
		"images/kuning.png",
		"images/table-sheet0.png",
		"images/tebakaksara-sheet0.png",
		"images/terjemahaksara-sheet0.png",
		"images/susunaksara-sheet0.png",
		"images/kartuaksara-sheet0.png",
		"images/pilihpermainan-sheet0.png",
		"images/lvl-sheet0.png",
		"images/pilihlevel-sheet0.png",
		"images/desc-sheet0.png",
		"images/btl-sheet0.png",
		"images/btl-sheet1.png",
		"images/keluar-sheet0.png",
		"images/info-sheet0.png",
		"images/tentang-sheet0.png",
		"images/info2-sheet0.png",
		"images/info2-sheet1.png",
		"images/kartu-sheet0.png",
		"images/kartu-sheet1.png",
		"images/soal_terjemahan-sheet0.png",
		"images/soal_terjemahan-sheet1.png",
		"images/soal_terjemahan-sheet2.png",
		"images/soal_terjemahan-sheet3.png",
		"images/soal_terjemahan-sheet4.png",
		"images/soal_terjemahan-sheet5.png",
		"images/soal_terjemahan-sheet6.png",
		"images/soal_terjemahan-sheet7.png",
		"images/soal_terjemahan-sheet8.png",
		"images/terjemahkanaksaradibawah_-sheet0.png",
		"images/bgsusun-sheet0.png",
		"images/aksara-sheet0.png",
		"images/aksara-sheet1.png",
		"images/aksara-sheet2.png",
		"media/suara cecek 3.ogg",
		"media/suara_surang-2.ogg",
		"media/button.ogg",
		"media/gameover.ogg",
		"media/kalah.ogg",
		"media/right-_bells_.ogg",
		"media/select.ogg",
		"media/suarajam.ogg",
		"media/victory_1.ogg",
		"media/wrong.ogg",
		"media/yey-child_2.ogg",
		"media/1_star.ogg",
		"media/2_star.ogg",
		"media/3_star.ogg",
		"media/lose.ogg",
		"media/success.m4a",
		"media/success.ogg",
		"media/salah.ogg",
		"media/cheer_kids.ogg",
		"media/goak.ogg",
		"media/suara_12.ogg",
		"media/suara_2.ogg",
		"media/suara_5.ogg",
		"media/suara_11.ogg",
		"media/suara_0.ogg",
		"media/suara_15.ogg",
		"media/suara_4.ogg",
		"media/suara_9.ogg",
		"media/suara_10.ogg",
		"media/suara_1.ogg",
		"media/suara_13.ogg",
		"media/suara_17.ogg",
		"media/suara_14.ogg",
		"media/suara_3.ogg",
		"media/suara_7.ogg",
		"media/suara_6.ogg",
		"media/suara_8.ogg",
		"media/suara_16.ogg",
		"media/suara cecek 2.ogg",
		"media/suara cecek 4.ogg",
		"media/suara cecek.ogg",
		"media/suara ng.ogg",
		"media/suara-r.ogg",
		"media/suara-surang.ogg",
		"media/suara bisah 2.ogg",
		"media/suara bisah 3.ogg",
		"media/suara bisah.ogg",
		"media/suara h.ogg",
		"media/suara adeg adeg 2.ogg",
		"media/suara adeg adeg.ogg",
		"media/suara e'.ogg",
		"media/suara e.ogg",
		"media/suara i.ogg",
		"media/suara o.ogg",
		"media/suara suku 2.ogg",
		"media/suara suku.ogg",
		"media/suara taleng 2.ogg",
		"media/suara taleng tedong 2.ogg",
		"media/suara taleng tedong.ogg",
		"media/suara taleng.ogg",
		"media/suara u.ogg",
		"media/suara ulu 2.ogg",
		"media/suara ulu.ogg",
		"media/suara pepet.ogg",
		"media/suara pepet 2.ogg",
		"media/suara guwung 2.ogg",
		"media/suara guwung r.ogg",
		"media/suara guwung.ogg",
		"media/suara ia.ogg",
		"media/suara nania 2.ogg",
		"media/suara nania.ogg",
		"media/suara suku kembung 2.ogg",
		"media/suara suku kembung.ogg",
		"media/suara ua.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}